name: Test Build Workflow

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  build-test:
    runs-on: ubuntu-22.04

    steps:
      # 1️⃣ Checkout repo (optional)
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2️⃣ Install build dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      # 3️⃣ Create a simple C program
      - name: Create test program
        run: |
          echo '#include <stdio.h>\nint main(){printf("Hello GitHub Actions!\\n"); return 0;}' > test.c

      # 4️⃣ Compile the C program
      - name: Compile test program
        run: gcc test.c -o test

      # 5️⃣ Run the compiled program
      - name: Run test program
        run: ./test

      # 6️⃣ Upload artifact (optional)
      - name: Upload compiled binary
        uses: actions/upload-artifact@v4
        with:
          name: test-binary
          path: test
