name: OnePlus 12R Kernel Build

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-kernel:
    runs-on: ubuntu-22.04
    env:
      ARCH: arm64
      CROSS_COMPILE: aarch64-linux-gnu-

    steps:
      # 1️⃣ Checkout kernel source
      - name: Checkout source
        uses: actions/checkout@v4

      # 2️⃣ Install dependencies
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            bc bison flex git make clang lld \
            libssl-dev build-essential gcc-aarch64-linux-gnu wget

      # 3️⃣ Detect Makefile folder
      - name: Detect Makefile folder
        id: detect_makefile
        run: |
          makefile_path=$(find . -name Makefile | head -n 1)
          makefile_dir=$(dirname "$makefile_path")
          echo "Detected Makefile directory: $makefile_dir"
          echo "MAKEFILE_DIR=$makefile_dir" >> $GITHUB_ENV

      # 4️⃣ Detect first available defconfig
      - name: Detect defconfig
        id: detect_defconfig
        run: |
          echo "Listing available defconfigs:"
          defconfig_file=$(ls $MAKEFILE_DIR/arch/arm64/configs | grep defconfig | head -n 1)
          echo "Detected defconfig: $defconfig_file"
          echo "DEFCONFIG=$defconfig_file" >> $GITHUB_ENV

      # 5️⃣ Load kernel config
      - name: Load kernel config
        run: make O=out ARCH=${ARCH} ${{ env.DEFCONFIG }}

      # 6️⃣ Build kernel
      - name: Build kernel
        run: |
          cd $MAKEFILE_DIR
          mkdir -p out
          make O=out ARCH=${ARCH} $DEFCONFIG
          make O=out ARCH=${ARCH} -j$(nproc) CROSS_COMPILE=${CROSS_COMPILE}

      # 7️⃣ Check output files
      - name: Check output files
        run: ls -R $MAKEFILE_DIR/out/arch/arm64/boot || true

      # 8️⃣ Collect artifacts
      - name: Collect kernel artifact
        run: |
          mkdir -p build_output
          cp $MAKEFILE_DIR/out/arch/arm64/boot/Image* build_output/
          cp $MAKEFILE_DIR/out/arch/arm64/boot/dtbo.img build_output/ || true
          cp $MAKEFILE_DIR/out/arch/arm64/boot/vendor_boot.img build_output/ || true
          ls -lh build_output/

      # 9️⃣ Upload artifacts
      - name: Upload kernel artifact
        uses: actions/upload-artifact@v4
        with:
          name: OnePlus12R-Kernel
          path: build_output/
