name: Kernel Build Auto

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      # 1️⃣ Checkout kernel source
      - name: Checkout source
        uses: actions/checkout@v4

      # 2️⃣ Install dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            bc bison flex git make gcc clang lld \
            libssl-dev build-essential

      # 3️⃣ Detect Makefile folder
      - name: Detect Makefile folder
        id: detect_makefile
        run: |
          makefile_path=$(find . -name Makefile | head -n 1)
          makefile_dir=$(dirname "$makefile_path")
          echo "Detected Makefile directory: $makefile_dir"
          echo "MAKEFILE_DIR=$makefile_dir" >> $GITHUB_ENV

      # 4️⃣ Detect first available defconfig
      - name: Detect first available defconfig
        id: detect_defconfig
        run: |
          echo "Listing available defconfigs:"
          defconfig_file=$(ls $MAKEFILE_DIR/arch/arm64/configs | grep defconfig | head -n 1)
          echo "Detected defconfig: $defconfig_file"
          echo "DEFCONFIG=$defconfig_file" >> $GITHUB_ENV

      # 5️⃣ Build kernel
      - name: Build kernel
        run: |
          cd $MAKEFILE_DIR
          export ARCH=arm64
          export SUBARCH=arm64
          export CC=clang
          export CROSS_COMPILE=aarch64-linux-gnu-

          mkdir -p out
          echo "Building kernel with $DEFCONFIG..."
          make O=out ARCH=arm64 $DEFCONFIG
          make O=out ARCH=arm64 -j$(nproc)

      # 6️⃣ Debug output
      - name: Check output files
        run: ls -R $MAKEFILE_DIR/out/arch/arm64/boot || true

      # 7️⃣ Upload artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kernel-build
          path: |
            $MAKEFILE_DIR/out/arch/arm64/boot/Image*
            $MAKEFILE_DIR/out/arch/arm64/boot/dtbo.img
            $MAKEFILE_DIR/out/arch/arm64/boot/vendor_boot.img
