name: Kernel Build Auto

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      # 1️⃣ Checkout source
      - name: Checkout source
        uses: actions/checkout@v4

      # 2️⃣ Install dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            bc bison flex git make gcc clang lld \
            libssl-dev build-essential

      # 3️⃣ Detect defconfig automatically
      - name: Detect first available defconfig
        id: detect_defconfig
        run: |
          echo "Listing available defconfigs:"
          defconfig_file=$(ls arch/arm64/configs | grep defconfig | head -n 1)
          echo "Detected defconfig: $defconfig_file"
          echo "DEFCONFIG=$defconfig_file" >> $GITHUB_ENV

      # 4️⃣ Build kernel using detected defconfig
      - name: Build kernel
        run: |
          export ARCH=arm64
          export SUBARCH=arm64
          export CC=clang
          export CROSS_COMPILE=aarch64-linux-gnu-

          mkdir -p out
          echo "Building kernel with $DEFCONFIG..."
          make O=out ARCH=arm64 $DEFCONFIG
          make O=out ARCH=arm64 -j$(nproc)

      # 5️⃣ Debug output
      - name: Check output files
        run: ls -R out/arch/arm64/boot || true

      # 6️⃣ Upload artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kernel-build
          path: |
            out/arch/arm64/boot/Image*
            out/arch/arm64/boot/dtbo.img
            out/arch/arm64/boot/vendor_boot.img
