name: OnePlus 12R Kernel Build Test

on:
  workflow_dispatch:        # Manual trigger se test
  push:
    branches: ["main"]      # Optional, har push pe bhi run

jobs:
  test-build:
    runs-on: ubuntu-22.04
    env:
      ARCH: arm64
      CROSS_COMPILE: aarch64-linux-gnu-
      DEFCONFIG: allmodconfig  # Generic config for testing

    steps:
      # 1️⃣ Checkout kernel source
      - name: Checkout Kernel Source
        run: |
          git clone --depth=1 https://github.com/OnePlus12R-development/android_kernel_oneplus_sm8550.git kernel

      # 2️⃣ Install build dependencies
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bc bison flex git make clang lld \
            libssl-dev build-essential gcc-aarch64-linux-gnu wget

      # 3️⃣ Check if Makefile exists
      - name: Check Makefile
        run: |
          if [ -f kernel/Makefile ]; then
            echo "Makefile found ✅"
          else
            echo "Makefile missing ❌"
            exit 1
          fi

      # 4️⃣ Load kernel config (dry-run)
      - name: Load kernel config
        run: make O=out ARCH=${ARCH} ${DEFCONFIG} -C kernel

      # 5️⃣ Dry-run build (fast check)
      - name: Dry-run build
        run: make O=out ARCH=${ARCH} -C kernel help

      # 6️⃣ Confirm output folder
      - name: Check output folder
        run: ls -lh kernel/out || echo "Output folder not created yet"
