name: Kernel Build

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      # 1️⃣ Checkout kernel source
      - name: Checkout source
        uses: actions/checkout@v4

      # 2️⃣ Install required packages
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            bc bison flex git make gcc clang lld \
            libssl-dev build-essential

      # 3️⃣ List available defconfigs
      - name: List available defconfigs
        run: |
          echo "Available defconfigs:"
          ls arch/arm64/configs | grep defconfig || true

      # 4️⃣ Build kernel
      - name: Build kernel
        run: |
          export ARCH=arm64
          export SUBARCH=arm64
          export CC=clang
          export CROSS_COMPILE=aarch64-linux-gnu-

          mkdir -p out
          echo "Building kernel with generic_auto_defconfig..."
          make O=out ARCH=arm64 generic_auto_defconfig
          make O=out ARCH=arm64 -j$(nproc)

      # 5️⃣ Debug: check output files
      - name: Debug check files
        run: ls -R out/arch/arm64/boot || true

      # 6️⃣ Upload build artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kernel-build
          path: |
            out/arch/arm64/boot/Image*
            out/arch/arm64/boot/dtbo.img
            out/arch/arm64/boot/vendor_boot.img
